# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Pushing to github repo
          script:
            - echo "Uploading to github repo"
            - git push --mirror git@github.com:dapize/hlds.git
      - step:
          name: Pushing to Dockerhub
          script:
            - docker build -t dapize/hlds:latest --no-cache .
            - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            - docker push dapize/hlds:latest
          services:
            - docker
